#!/usr/bin/env python3

import os
import sys

def import_sorter(new_imports):
    imports = [
        "import keras\n",
        "import matplotlib\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "import tensorflow\n"]

    for new_import in args[2:]:
        imports.append(f"import {new_import}\n")

    imports.sort()
    imports[-1] += "\n"

    return imports

def filename_ext(name):
    return name if name.endswith((".py", ".txt")) else name + ".py"

if __name__ == "__main__":
    args = [i.strip() for i in sys.argv[1:]]

    if len(args) == 0:
        print("\nEnter commands\n"
              "Command format follows this\n"
              "<type> <filename> <extra libraries>\n")
        exit()
    
    imports = import_sorter(args[2:])
    
    if args[0].lower() == "data":
        if len(args) > 1:
            if args[1]:
                with open(filename_ext(args[1]), "w+") as f:
                    f.writelines(imports)
        else:
            print("No file name inputted")
